#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\n>> Pre-push Hook: Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|main)"

if [[ $1 != *"$BRANCH"* ]]
then
  echo "\n🚫 You must use (git push origin $BRANCH).\n" && exit 1
fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR."
fi

echo -e "\n>> Finish checking branch name"

exit 0
